### ISSUE TITLE
Memory Issue while running model as REST service

### ISSUE THREAD

**Issue by Rohit8y** [SapienzaNLP/ewiser#10]
I'm using a REST service to run WSD model. But it's RAM keeps on increasing as I the number of hits increase. I was testing how much RAM will be enough for this, so at last I used a 64GB server, and it consumed all of it.

This is the code for rest service:-

import requests
import re
import os
import time
import json
from flask import jsonify
from time import sleep
from json import dumps
from flask import Flask, request
from ewiser.spacy.disambiguate import Disambiguator
import spacy

nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])
wsd = Disambiguator("/content/ewiser.semcor+wngt.pt", lang="en")
nlp.add_pipe(wsd, last=True)
app = Flask(__name__)
@app.route("/wsd", methods=['POST'])
def wsd():

	print('service ---------------(( + _ + ))----------------- started')
	item = {}
	x = request.get_json()
	print('+++++++++++++++++++++++++++++++++', x)
	sent = x['text'] 
	doc = nlp(sent)
	List = []
	for w in doc:
		if w._.offset:
			print(w.text, w.lemma_, w.pos_, w._.offset, w._.synset.definition())
			itm= {}
			itm['lemma']=w.lemma_
			itm['synset']=w._.offset
			itm['gloss']=w._.synset.definition()
			List.append(itm)
	print(List) 
	return jsonify(List)

if __name__ == "__main__":
	#app.debug = True
	app.run(host='localhost', port=7777)

**Comment by Rohit8y** [comment]
@mbevila

**Comment by mirfan899** [comment]
I think you need to run the code in a single process:

```python
app.run(host='localhost', port=7777, threaded=False, processes=1)
```

**Comment by mbevila** [comment]
@Valahaar

**Comment by Valahaar** [comment]
I've encountered this before, I solved it by installing jmalloc (
https://github.com/jemalloc/jmalloc) and using it in place of the standard
malloc, then you can launch your python script like this:
LD_PRELOAD=/usr/local/lib/libjemalloc.so python ...

More info should be on the jmalloc repo itself. Hope this helps!

Cheers,
Niccolò

**Comment by mirfan899** [comment]
Does not exist.

https://github.com/jemalloc/jmalloc

This is correct url.
https://github.com/jemalloc/jemalloc

**Comment by Valahaar** [comment]
Sorry, kinda hard to type from the phone, that's the link!

**Comment by mbevila** [comment]
@mirfan899 have you solved this?

**Comment by mirfan899** [comment]
Yes, I used the single thread, and its working fine for me.
