### ISSUE TITLE
Spacy 3 not compatible

### ISSUE THREAD

**Issue by mirfan899** [SapienzaNLP/ewiser#12]
I tried to use spacy 3 but it gives an error.

![ewiser](https://user-images.githubusercontent.com/3822565/127957456-a5d9904e-55d1-4736-a8e2-fe2da557c132.png)

**Comment by mirfan899** [comment]
got it working with spacy 3.

**Comment by LifeIsStrange** [comment]
@mirfan899 what fixed the issue?

**Comment by brucewlee** [comment]
```
import spacy
from ewiser.spacy.disambiguate import Disambiguator
from spacy.language import Language

nlp = spacy.load("en_core_web_sm", disable=['parser', 'ner'])

@Language.factory('wsd')
def wsd_engine(nlp, name):
    return Disambiguator('ewiser/ewiser.semcor+wngt.pt', lang="en")

nlp.add_pipe('wsd', last=True)

doc = nlp("I want the peach cobbler.")

for w in doc:
    if w._.offset:
        print(w.text, w.lemma_, w.pos_, w._.offset, w._.synset.definition())
```

**Comment by brucewlee** [comment]
@LifeIsStrange Here you go. It's a simple trick for spaCy 3 requirements. @mbevila It'd be great if we also modified the code in disambiguate.py. By the way, is there a way to see sense keys?
