### ISSUE TITLE
multilingual datasets and model

### ISSUE THREAD

**Issue by lwmlyy** [SapienzaNLP/ewiser#2]
Hi, nice work there. Could you please detail the multilingual dataset version ('all' or 'wn') and also the multilingual BERT version (base or large)?

**Comment by mbevila** [comment]
We used the 'wn' version. The BERT model is the 'bert-base-multilingual-cased' one.

**Comment by lwmlyy** [comment]
I see, thx. I wonder if there is any special reason why the large model is not used.

**Comment by mbevila** [comment]
There wasn't a BERT multilingual large model when the experiments were performed. (Not sure there is one now). If you need a stronger multilingual model, you can use XLM-R, it is trivial to train one with our code. I could release a pre-trained checkpoint someday, if I see interest in this.

**Comment by lwmlyy** [comment]
OK, I might try it myself with XLM-R. Thanks.
