### ISSUE TITLE
Babelnet 4.0.1 Dependency

### ISSUE THREAD

**Issue by Domattee** [SapienzaNLP/ewiser#6]
Hello,

It seems that disambiguation for languages other than English requires Babelnet 4.0.1, which is not available anymore.  We tried just replacing the BabelNet 4 references in the bash scripts with those to Babelnet 5.0, but this does not work and producing the offset/lemmapos dictionary files from a newer version seems likely to introduce errors from altered offsets.
Download links for the old API from other locations are all dead.

Do you have plans to update this to BabelNet 5.0, or to make 4.0.1 available for this project?
How else would you suggest using the pretrained Multilingual model for other languages?

Thanks

**Comment by mbevila** [comment]
@Domattee We have updated the README.md with a new link to download the indices! Now the 4.0.1 indices are also available on http://nlp.uniroma1.it/resources/.

**Comment by Domattee** [comment]
Thank you very much, we got it running.
