### ISSUE TITLE
Notebooks?

### ISSUE THREAD

**Issue by rdaniel** [SapienzaNLP/ewiser#9]
The README says "EWISER can be used as a spacy plugin. Please check annotate.py and notebooks/inspect_wsd.py". However, there doesn't seem to be any notebooks/ directory. It looks like it is in the .gitignore file. Can you either add that directory to the repo or delete the mention of it from the README?

**Comment by mbevila** [comment]
Thanks for spotting this. I will maybe add the notebooks later on, right now they are in quite a sorry state.
